/* Generated by Together */

#ifndef ARCHIVOADJUNTO_H
#define ARCHIVOADJUNTO_H
#include "Base64.h"
class ListaArchivosAdjuntos;
class ArchivoAdjunto {
public:

    int readData();

    string encode();

private:    
    string filename;
    BYTE * data;
    int size;

    /** @link dependency */
    /*# Base64 lnkBase64; */
};
#endif //ARCHIVOADJUNTO_H