/* Generated by Together */

#ifndef AUTHLOGIN_H
#define AUTHLOGIN_H
#include "AuthSMTP.h"
class AuthLogin : public AuthSMTP {
    

public:    

    void doLogin();
};
#endif //AUTHLOGIN_H