/* Generated by Together */

#ifndef CORREO_H
#define CORREO_H
#include "ServidorEnvio.h"
#include "ArchivoAdjunto.h"
#include "ListaDestinatarios1.h"

typedef std::vector<ArchivoAdjunto*> ListaArchivosAdjuntos;


class Correo {



public:

    void addAdjunto(string filename);

    void removeAdjunto(int i);

    void clearAdjuntos();

    ArchivoAdjunto & getAdjunto(int i);

    int getTotalAdjuntos();

protected:

    int addDestino(int tipo, string & quien);

    bool removeDestino(int tipo, string & quien );

    void clearDestinos(int tipo);

    string getDestino(int tipo, int i);

    int getTotalDestinos(int tipo);

    /** @link aggregation */
    vector < ArchivoAdjunto * > adjuntos;
    /** @link aggregation
     * @supplierCardinality 3*/
    ListaDestinatarios destinos[3];
    string asunto;
    string cuerpo;

    /**
     * @associates <{Correo::TipoPrioridad}> 
     */
    TipoPrioridad prioridad;
};
#endif //CORREO_H