/* Generated by Together */

#ifndef SERVIDORESDISPONIBLES_H
#define SERVIDORESDISPONIBLES_H
#include "ServidorEnvio.h"
#include "ServidorSMTP.h"
#include "ServidorMAPI.h"
#include "LibConfiguracion/Configuracion.h"

class ServidoresDisponibles {
public:

    static void CrearServidor(Configuracion*);

private:

    /** @link dependency */
    /*# ServidorSMTP lnkServidorSMTP; */

    /** @link dependency */
    /*# ServidorMAPI lnkServidorMAPI; */

    /** @link dependency */
    /*# Configuracion lnkConfiguracion; */
};
#endif //SERVIDORESDISPONIBLES_H