/* Generated by Together */

#ifndef SERVIDORSMTP_H
#define SERVIDORSMTP_H
#include "ServidorEnvio.h"
#include "AuthSMTPFactory.h"
#include "Base64.h"
class AuthSMTP;
class RedCliente;

class ServidorSMTP : public ServidorEnvio {
public:

    static ServidorEnvio * Crear();

    virtual void conectar();

    virtual void desconectar();

    void enviar();


private:    

    /** @supplierCardinality 1 */
    RedCliente * m_socket;
    int host;
    int port;
    int user;
    int password;    

    /**
         *@link aggregation
         *@supplierCardinality 1
         * @supplierQualifier authSMTP
         */
    AuthSMTP * authSMTP;

    /** @link dependency */
    /*# AuthSMTPFactory lnkAuthSMTPFactory; */

    /** @link dependency */
    /*# Base64 lnkBase64; */
protected:


    void transmitir();

    string getCabecera();

    string getCuerpo();

protected:


protected:
};
#endif //SERVIDORSMTP_H