/* Generated by Together */

#include "LibCorreo/Correo.h"

void Correo::clearAdjuntos(){}
void Correo::removeAdjunto(int i){}
void Correo::addAdjunto(string filename){}
bool Correo::removeDestino(int tipo, string & quien ){}
void Correo::clearDestinos(int tipo){}

int Correo::getTotalAdjuntos(){}
class ArchivoAdjunto;

int Correo::getTotalDestinos(int tipo){}

ArchivoAdjunto & Correo::getAdjunto(int i){}

int Correo::addDestino(int tipo, string & quien){}
