/* Generated by Together */

#include "LibCorreo/ServidorMAPI.h"

void ServidorMAPI::isMapiInstalled(){}
bool ServidorMAPI::unloadMapiDLL(){}
bool ServidorMAPI::loadMapiDLL(){}

void ServidorMAPI::enviar(){}
void ServidorMAPI::desconectar(){ }
void ServidorMAPI::conectar(){ }
ServidorEnvio * ServidorMAPI::Crear(){}
