/* Generated by Together */

#include "LibCorreo/ServidorEnvio.h"

void ServidorEnvio::isConectado(){}
ServidorEnvio * ServidorEnvio::Crear(){}

void ::ServidorEnvio::ServidorEnvio(ConfiguracionServidor p0){}
