/* Generated by Together */

#include "LibCorreo/ServidorSMTP.h"

string ServidorSMTP::getCabecera(){}
string ServidorSMTP::getCuerpo(){}
void ServidorSMTP::transmitir(){}

ServidorEnvio * ServidorSMTP::Crear(){}

void ServidorSMTP::enviar(){}
void ServidorSMTP::desconectar(){ }
void ServidorSMTP::conectar(){ }

